// iPhone (sin pantalla completa en Safari): aviso de "Agregar a inicio" en los menús, se cierra y no vuelve
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const { spawn } = require('child_process');
(async () => {
  const srv = spawn('python3', ['-m', 'http.server', '8772'], { cwd: process.cwd() + '/web', stdio: 'ignore' });
  await new Promise(r => setTimeout(r, 900));
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 844, height: 390 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
  await ctx.addInitScript({ path: 'mocksupa.js' });
  await ctx.addInitScript(() => { window.requestAnimationFrame = () => 0; delete Element.prototype.requestFullscreen; delete Element.prototype.webkitRequestFullscreen; });
  await ctx.route('**/config.js', r => r.fulfill({ contentType: 'text/javascript', body: 'window.APYV_CONFIG = { client: window.__mockClient, ice: [] };' }));
  let pass = 0, fail = 0; const errs = [];
  const ok = (n, c, info) => { if (c) pass++; else fail++; console.log(`${c ? 'OK  ' : 'FAIL'} ${n}${info !== undefined ? '  → ' + info : ''}`); };
  const p = await ctx.newPage(); p.on('pageerror', e => errs.push(e.message));
  await p.goto('http://localhost:8772/index.html'); await p.waitForTimeout(500);
  await p.evaluate(() => { for (let i = 0; i < 3; i++) step(); render(); });
  const vis = () => p.evaluate(() => { const e = document.getElementById('iosfs'); return !!e && e.style.display !== 'none' && e.getBoundingClientRect().width > 0; });
  ok('en el menú aparece cómo tener pantalla completa en iPhone', await vis());
  await p.screenshot({ path: 'shots/look/iosfs.png' });
  await p.evaluate(() => { APP.startBattle({ players: [{ port: 0, char: 'puentin', dev: 'touch' }, { port: 1, char: 'nacho', cpu: 1 }], stage: 'temple', rules: { mode: 'stock', stocks: 3, items: 0 } }); for (let i = 0; i < 5; i++) step(); render(); });
  ok('en la pelea no estorba', !(await vis()));
  await p.evaluate(() => { BATTLE = null; APP.go('main'); step(); render(); });
  await p.tap('#iosfs button'); await p.evaluate(() => { step(); render(); });
  ok('se cierra con ✕', !(await vis()));
  await p.reload(); await p.waitForTimeout(400); await p.evaluate(() => { for (let i = 0; i < 3; i++) step(); render(); });
  ok('y ya no vuelve a salir', !(await vis()));
  // Safari con barras (de lado la ventana es más baja que la pantalla): deslizar hacia arriba las esconde
  const c2 = await browser.newContext({ viewport: { width: 844, height: 318 }, screen: { width: 390, height: 844 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
  await c2.addInitScript({ path: 'mocksupa.js' });
  await c2.addInitScript(() => { window.requestAnimationFrame = () => 0; delete Element.prototype.requestFullscreen; delete Element.prototype.webkitRequestFullscreen; });
  await c2.route('**/config.js', r => r.fulfill({ contentType: 'text/javascript', body: 'window.APYV_CONFIG = { client: window.__mockClient, ice: [] };' }));
  const q = await c2.newPage(); q.on('pageerror', e => errs.push(e.message));
  await q.goto('http://localhost:8772/index.html'); await q.waitForTimeout(500);
  await q.evaluate(() => { for (let i = 0; i < 3; i++) step(); render(); });
  const st = () => q.evaluate(() => { const e = document.getElementById('iosfs'), r = e && e.getBoundingClientRect(), g = canvas.getBoundingClientRect(); return { cls: e ? e.className : '', vis: !!e && e.style.display !== 'none' && r.width > 0, top: r ? Math.round(r.top) : -1, roll: document.documentElement.classList.contains('iosroll'), fight: document.documentElement.classList.contains('fight'), ta: getComputedStyle(document.body).touchAction, sh: document.scrollingElement.scrollHeight, gx: Math.round(g.left), gy: Math.round(g.top), gw: Math.round(g.width), sy: Math.round(scrollY) }; });
  const a0 = await st();
  ok('con barras: aviso grande arriba de deslizar hacia arriba', a0.vis && a0.cls === 'swipe' && a0.top < 40, JSON.stringify(a0));
  ok('la página tiene por dónde deslizarse y en el menú se puede', a0.roll && a0.sh > 318 * 2 && a0.ta === 'pan-y', JSON.stringify(a0));
  await q.screenshot({ path: 'shots/look/iosswipe.png' });
  await q.evaluate(() => { window.scrollTo(0, 400); step(); render(); });
  const a1 = await st();
  ok('al deslizar, el juego se queda quieto en medio', a1.sy > 0 && a1.gx === a0.gx && a1.gy === a0.gy && a1.gw === a0.gw, JSON.stringify({ a0, a1 }));
  await q.setViewportSize({ width: 844, height: 390 }); await q.evaluate(() => { step(); render(); });
  const a2 = await st();
  ok('sin barras ya no pide deslizar (queda el consejo de inicio)', a2.cls === 'home', JSON.stringify(a2));
  await q.evaluate(() => { APP.startBattle({ players: [{ port: 0, char: 'nicole', dev: 'touch' }, { port: 1, char: 'nacho', cpu: 1 }], stage: 'temple', rules: { mode: 'stock', stocks: 3, items: 0 } }); for (let i = 0; i < 5; i++) step(); render(); });
  const a3 = await st();
  ok('en la pelea ningún toque desliza la página (las barras no regresan)', a3.fight && a3.ta === 'none' && !a3.vis, JSON.stringify(a3));
  // (cambiar el tamaño de la ventana en la prueba también cambia la "pantalla": una página nueva vuelve a tener barras)
  const q2 = await c2.newPage(); q2.on('pageerror', e => errs.push(e.message));
  await q2.goto('http://localhost:8772/index.html'); await q2.waitForTimeout(400); await q2.evaluate(() => { for (let i = 0; i < 3; i++) step(); render(); });
  const b0 = await q2.evaluate(() => IOSFS.shownState);
  await q2.tap('#iosfs button'); await q2.evaluate(() => { step(); render(); });
  const b1 = await q2.evaluate(() => ({ st: IOSFS.shownState, off: IOSFS.swipeOff, home: localStorage.getItem('apyv-iosfs') }));
  ok('el aviso de deslizar se cierra y deja el consejo de inicio', b0 === 'swipe' && b1.off && b1.st === 'home' && b1.home !== '1', JSON.stringify({ b0, b1 }));
  ok('sin errores', errs.length === 0, errs.slice(0, 3).join(' | '));
  console.log(`\n${pass} OK, ${fail} FAIL`);
  await browser.close(); srv.kill(); process.exit(fail ? 1 : 0);
})();
