// RTT, compensación del reloj, promedio de 60 cuadros y retraso adaptable.
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const path=require('path');
(async()=>{const br=await chromium.launch();try{const p=await br.newPage();await p.addInitScript(()=>window.requestAnimationFrame=()=>0);await p.goto('file://'+path.resolve('index.html'));const out=await p.evaluate(()=>{
 const out=[],check=(name,pass,value)=>out.push({name,pass,value});if(typeof RollbackSession==='undefined')return [{name:'falta RollbackSession',pass:false}];let now=0,msg=[];
 const b=new Battle({seed:1,players:[{port:0,char:'nacho',dev:'q'},{port:1,char:'michi',dev:'r'}],stage:'city',rules:{stocks:99,time:0,items:0}},{demo:true});const r=new RollbackSession(b,{myPeer:'H',hostPeer:'H',owners:{0:'H',1:'G'},ep:7,now:()=>now,read:()=>blankState(),send:(k,v,to)=>{msg.push({k,v,to});return true}});
 r.tick();check('delay empieza en 2',r.delay===2,r.delay);check('manda ping directo',msg.some(m=>m.k==='rp'&&m.to==='G'));const ping=msg.find(m=>m.k==='rp');now=250;r.receive('rp2',{ep:7,id:ping.v.id},'G');r.tick();check('RTT alto sube a 3',r.delay===3&&r.rtts.get('G')===250,{delay:r.delay,rtt:r.rtts.get('G')});check('cambio de delay no deja hueco',r.real.get(0).has(3)&&r.real.get(0).has(4));r.resimAvg=13;r.tick();check('equipo lento sube a 4',r.delay===4,r.delay);
 const samples=Array(59).fill(5);r.clocks.set('G',samples);const before=r.frame;r.ticks=2;r.tick();check('no regula antes de 60 muestras',r.frame>before);r.clocks.set('G',Array(60).fill(5));const f=r.frame;r.ticks=2;r.tick();check('espera un step si va adelantado',r.frame===f&&r.ahead===5,{f,actual:r.frame,ahead:r.ahead});r.clocks.set('G',Array(60).fill(0));r.tick();check('reanuda con relojes emparejados',r.frame>f);
 return out;
});for(const x of out)console.log((x.pass?'OK   ':'FAIL ')+x.name+' '+JSON.stringify(x.value));const fail=out.filter(x=>!x.pass).length;console.log(out.length-fail+' OK, '+fail+' FAIL');process.exitCode=fail?1:0}finally{await br.close()}})().catch(e=>{console.error(e);process.exitCode=1});
