// Tres invitados, estrella por el anfitrión, canal fiable y red simulada.
const {chromium}=require('/opt/node22/lib/node_modules/playwright');const {spawn}=require('child_process');
(async()=>{const srv=spawn('python3',['-m','http.server','8773'],{cwd:process.cwd()+'/web',stdio:'ignore'});process.on('exit',()=>{try{srv.kill()}catch(e){}});const browser=await chromium.launch();let fail=0,ok=0;const errors=[];let pages=[];try{await new Promise(r=>setTimeout(r,1000));const ctx=await browser.newContext();await ctx.addInitScript({path:'mocksupa.js'});await ctx.addInitScript(()=>window.requestAnimationFrame=()=>0);await ctx.route('**/config.js',r=>r.fulfill({contentType:'text/javascript',body:'window.APYV_CONFIG={client:window.__mockClient,ice:[]};'}));pages=[];for(let i=0;i<4;i++){const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8773/index.html');pages.push(p)}
const ready=await pages[0].evaluate(async()=>{await Net.init();return typeof Net.room?.fastSend==='function'});if(!ready){console.log('FAIL falta fastSend/onFast');fail++;return}
const host=await pages[0].evaluate(()=>{Net.role='host';Net.set({role:'host',lob:{ph:'lobby'}});window.packets=[];Net.room.onFast('ri',e=>packets.push(e));Net.room.onState('rs',e=>packets.push(e));return Net.myPeer()});
for(let i=1;i<4;i++)await pages[i].evaluate(async([host,i])=>{await Net.init();Net.role='guest';Net.hostPeer=host;Net.set({role:'guest',join:host});window.packets=[];Net.room.onFast('ri',e=>packets.push(e));Net.room.onState('rs',e=>packets.push(e))},[host,i]);
await pages[0].waitForFunction(()=>Net.room.fastReady()&&Net.room._debug().links.length===3,{},{polling:100,timeout:20000});for(const p of pages.slice(1))await p.waitForFunction(()=>Net.room.fastReady(),{},{polling:100,timeout:10000});console.log('OK   3 conexiones con ambos canales');ok++;
await pages[1].evaluate(()=>Net.room.fastSend('ri',{p:1,f:10,ack:0,a:Array.from({length:10},(_,i)=>[i,0,0,0,2])}));await pages[0].waitForFunction(()=>packets.length===1,null,{polling:100});await pages[2].waitForFunction(()=>packets.length===1,null,{polling:100});await pages[3].waitForFunction(()=>packets.length===1,null,{polling:100});
const relay=await Promise.all(pages.map(p=>p.evaluate(()=>packets.filter(e=>e.k==='ri').map(e=>({n:e.data.a.length,first:e.data.a[0][0],p:e.data.p,peer:e.peer})))));const guest=await pages[1].evaluate(()=>Net.myPeer());const pass=relay[0][0]?.n===8&&relay[0][0]?.first===2&&relay[1].length===0&&relay[2][0]?.peer===guest&&relay[3][0]?.peer===guest;console.log((pass?'OK   ':'FAIL ')+'estrella y 8 entradas '+JSON.stringify(relay));pass?ok++:fail++;
await pages[0].evaluate(()=>Net.room.stateSend('rs',{f:0,state:'x'.repeat(70000)}));for(const p of pages.slice(1))await p.waitForFunction(()=>packets.some(e=>e.k==='rs'&&e.data.state.length===70000),null,{polling:100});console.log('OK   estado de 70 KB por canal fiable');ok++;
await pages[1].evaluate(()=>{window.__netsim={delay:60,jitter:0,loss:1};Net.room.fastSend('ri',{p:1,f:11,ack:0,a:[[0,0,0,0,0]]});Net.room.stateSend('rs',{f:1,state:'fiable'})});await pages[0].waitForFunction(()=>packets.some(e=>e.k==='rs'&&e.data.state==='fiable'),null,{polling:100});await pages[0].waitForTimeout(100);const loss=await pages[0].evaluate(()=>!packets.some(e=>e.k==='ri'&&e.data.f===11));console.log((loss?'OK   ':'FAIL ')+'pérdida solo en canal no fiable');loss?ok++:fail++;
if(errors.length){console.log('ERRORES',errors);fail++}
}catch(e){fail++;console.log('DEBUG',JSON.stringify(await Promise.all(pages.map(p=>p.evaluate(()=>({room:Net.room?Net.room._debug():null,peers:Net.peers().map(x=>({peer:x.peer,p:x.presence}))})).catch(()=>null)))));throw e;}finally{await browser.close();srv.kill();console.log(ok+' OK, '+fail+' FAIL');process.exitCode=fail?1:0}})().catch(e=>{console.error(e);process.exitCode=1});
